<div class="container-fluid">
    <form action="Login" method="post">
        <div class="row">
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 text-center border shadow my-5">
                <h1>whatsapp</h1>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" name="user" id="floatingInput" placeholder="Usuario" autocomplete="off">
                    <label for="floatingInput">Usuario:</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" name="pass" id="floatingPassword" placeholder="Password" autocomplete="off">
                    <label for="floatingPassword">Contraseña:</label>
                </div>
                <input type="submit" value="Ingresar" name="btnIniciarSession" class="btn btn-outline-success my-3">
            </div>
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        </div>
    </form>
</div>