<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4"></div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4 ml-5 text-end">
            <h2><i>Mensaje de despedida</i></h2>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-1 col-sm-8 col-md-8 col-lg-8 border">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <form id="formMensajeDespedida">
                            <input type="text" class="form-control my-2" value="<?= $usuario ?>" readonly>
                            <textarea name="txtMensajeDespedida" class="form-control my-2" id="txtMensajeDespedida" cols="30" rows="10" placeholder="ingrese mensaje de despedida"></textarea>
                            <button class="btn btn-outline-dark my-3" id="btnIngresarMensajeDespedida">Ingresar</button>
                        </form>
                    </div>
                    <div class="col-12 col-sm-8 table-responsive text-center ScrollMinimo" style="overflow:auto; height:300px; width:500px;">
                        <form id="form_MensajeDespedida">
                            <table class="table table-hover border">
                                <thead>
                                    <tr>
                                        <th>Mensajes</th>
                                        <th>Fecha Hora</th>
                                        <th>Creador</th>
                                        <th>Accion</th>
                                    </tr>
                                </thead>
                                <tbody id="tablaMostrarMensajeDespedida">

                                </tbody>
                                <tfoot>
                                    <th></th>
                                    <th></th>
                                    <th><button class="btn btn-outline-danger" id="btnEliminarMensajeDespedida"><i class="fas fa-trash-alt"></i></button></th>
                                    <th></th>
                                </tfoot>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1 col-sm-1 col-md-1 col-lg-1"></div>
    </div>
</div>