<div class="container-fluid">
    <div class="row text-center p-3">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 text-center">
            <h3>Conversaciones</h3>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4">
            <form id="frmidparaconsultarDatatableConversacion">
                <input type="number" name="id" value="<?= $idAgente ?>" style="outline: none; border: 0;" readonly>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 border text-center">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre de la Sala</th>
                        <th>Nombre Cliente</th>
                        <th>Imagen Cliente</th>
                        <th>Abierto</th>
                    </tr>
                </thead>
                <tbody id="tabladialogs">

                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
    </div>
</div>