<div class="container-fluid" style="padding-bottom: 70px;">
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 text-center">
            <h2><i>Dashboard</i></h2>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
        <div class="col-12 col-sm-10 col-md-10 col-lg-10 col-xl-10">
            <!-- Agregando Campos -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <a href="" data-bs-toggle="modal" data-bs-target="#ModalTotal">
                            <div class="card text-white bg-danger mb-3" id="cardTotal" style="max-width: 18rem;" data-bs-toggle="tooltip" data-bs-placement="top" title="Acá se irán Acumulando la cantidad de Chats en Total que se encuentran sin eliminar">
                                <div class="card-header"><i class="far fa-comments fa-2x"></i></div>
                                <div class="card-body">
                                    <h5 class="card-title">Total</h5>
                                    <p class="card-text" id="CardSalasPendientes"></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <a href="" data-bs-toggle="modal" data-bs-target="#ModalAbiertos">
                            <div class="card text-white bg-warning mb-3" id="cardAbiertos" style="max-width: 18rem;" data-bs-toggle="tooltip" data-bs-placement="top" title="Acá se irán Acumulando la cantidad de Chats que se encuentran Abiertos">
                                <div class="card-header"><i class="far fa-comment-alt fa-2x"></i></div>
                                <div class="card-body">
                                    <h5 class="card-title">Abiertos</h5>
                                    <p class="card-text" id="CardSalasAbiertas"></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <a href="" data-bs-toggle="modal" data-bs-target="#ModalCerrados">
                            <div class="card text-white bg-secondary mb-3" id="cardCerrados" style="max-width: 18rem;" data-bs-toggle="tooltip" data-bs-placement="top" title="Acá se irán Acumulando la cantidad de Chats que se encuentran Resueltos">
                                <div class="card-header"><i class="fas fa-power-off fa-2x"></i></div>
                                <div class="card-body">
                                    <h5 class="card-title">Cerrados</h5>
                                    <p class="card-text" id="CardSalasCerradas"></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <a href="" data-bs-toggle="modal" data-bs-target="#ModalAsignados">
                            <div class="card text-white bg-success mb-3" id="cardAsignados" style="max-width: 18rem;" data-bs-toggle="tooltip" data-bs-placement="top" title="Acá se irán Acumulando la cantidad de Chats que se encuentran Asignados">
                                <div class="card-header"><i class="far fa-user fa-2x"></i></div>
                                <div class="card-body">
                                    <h5 class="card-title">Asignados</h5>
                                    <p class="card-text" id="CardSalasAsignadas"></p>
                                </div>
                            </div>
                        </a>

                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <a href="" data-bs-toggle="modal" data-bs-target="#ModalSeguimiento">
                            <div class="card text-white bg-primary mb-3" id="carSeguimiento" style="max-width: 18rem;" data-bs-toggle="tooltip" data-bs-placement="top" title="Acá se irán Acumulando la cantidad de Chats que se encuentran Seguimiento">
                                <div class="card-header"><i class="far fa-comment fa-2x"></i></div>
                                <div class="card-body">
                                    <h5 class="card-title">Seguimiento</h5>
                                    <p class="card-text" id="CardSalasAsignadas">//</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
    </div>
    <div class="row ml-5">
        <div class="col-12 col-sm-1 col-md-1 col-lg-2"></div>
        <div class="col-12 col-sm-10 col-md-10 col-lg-9 border shadow table-responsive">
            <form action="MostrandoDialogAsignadoAgente" id="frmChatAsignados" method="post">
                <table id="TableDasboard" class="table table-hover text-center">
                    <thead>
                        <tr>
                            <th>
                                Seleccionar
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Apellido
                            </th>
                            <th>
                                usuario
                            </th>
                            <th>
                                Chat Pendientes
                            </th>
                            <th>
                                Chat Abiertos
                            </th>
                        </tr>
                    </thead>
                    <tbody id="ChatAsignadosAgentes">


                    </tbody>
                    <tfoot>
                        <tr>
                            <td><button class="btn btn-outline-success" type="submit" id="btnMostrarChatAgente">Mostrar</button></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
        <div class="col-12 col-sm-1 col-md-1 col-lg-1"></div>
    </div>
</div>
<!-- Modal Total -->
<div class="modal fade" id="ModalTotal" tabindex="-1" aria-labelledby="InfoModalTotal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="InfoModalTotal">Total de Salas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body table-responsive CajaChat">
                <table class="table table-hover text-center border shadow">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th colspan="3"><label for="FiltroTablaTotal">Ingrese Criterios de Busqueda</label></th>
                            <th>
                                <form id="frmFiltrarTotalSala"><input type="text" name="FiltroTablaTotal" class="form-control" id="FiltroTablaTotal" placeholder="Ingrese Id"></form>
                            </th>
                        </tr>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Image</th>
                            <th>Asignador</th>
                            <th>Asignado a</th>
                            <th>Abrir Sala</th>
                        </tr>
                    </thead>
                    <tbody id="TablaChatAcumulado">

                    </tbody>
                    <tfoot>

                    </tfoot>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>




<!-- Modal Abiertos -->
<div class="modal fade" id="ModalAbiertos" tabindex="-1" aria-labelledby="InfoModalAbiertos" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="InfoModalAbiertos">Total de Salas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Abiertos
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



<!-- Modal Cerrados -->
<div class="modal fade" id="ModalCerrados" tabindex="-1" aria-labelledby="InfoModalCerrados" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="InfoModalCerrados">Total de Salas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Cerrados
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



<!-- Modal Asignados -->
<div class="modal fade" id="ModalAsignados" tabindex="-1" aria-labelledby="InfoModalAsignados" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="InfoModalAsignados">Total de Salas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Asignados
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



<!-- Modal Seguimiento -->
<div class="modal fade" id="ModalSeguimiento" tabindex="-1" aria-labelledby="InfoModalSeguimiento" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="InfoModalSeguimiento">Total de Salas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Seguimiento
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>