<div class="offcanvas offcanvas-start text-center my-5" tabindex="-1" id="Conversaciones" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <div class="container-fluid">
            <div class="row">
                <center>
                    <h3><i>Select Insurance</i></h3>
                </center>
            </div>
            <div class="row">
                <div class="col-12">
                    <form action="" method="post">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="Filtro" id="floatingInput" placeholder="Usuario" autocomplete="off">
                            <label for="floatingInput"><i class="fas fa-search"></i> Filtrar</label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="offcanvas-body ScrollMinimo shadow border">
        <?php while ($rows = mysqli_fetch_assoc($consulta)) : ?>
            <form action="AbrirSalaChat" method="post">
                <div class="d-grid">
                    <button type="submit" name="btnAbrirChat" value="<?= $rows['id'] ?>" class="btn btn-outline-success rounded-1" target="__blank">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-3 col-md-3 col-lg-3 col-xl-3">
                                    <img src="<?php if (!empty($rows['image'])) {
                                                    print $rows['image'];
                                                } else {
                                                    print 'app\master\views\assets\css\images\sinfoto.webp';
                                                }  ?>" class="img-thumbnail rounded float-start" width="40px">
                                </div>
                                <div class="col-6 col-md-6 col-lg-6 col-xl-6">
                                    <?= $rows['name'] ?>
                                </div>
                                <div class="col-3 col-md-3 col-lg-3 col-xl-3">
                                    <div class="dropdown">
                                        <a class="btn btn-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="fas fa-cog fa-1x"></i>
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <li><a class="dropdown-item" href="index.php?controller=TransferirChat&Id=<?= $rows['id'] ?>">Transferir</a></li>
                                            <li><a class="dropdown-item" href="#">Perfil</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </button>
                </div>
            </form>
        <?php endwhile; ?>
    </div>
</div>




